### PR TITLE
Add Typescript types

### PR DESCRIPTION
**Pull request by Ekman**
Add Typescript types for type checking support. Typically used by IDEs as well to provide information.

### CODE REVIEW

**Comment by Ekman** [comment]
Ping @vvmspace

**Comment by Ekman** [comment]
I'd be forever grateful for a merge here and a version update to the NPM package registry :)

**Comment by Ekman** [comment]
I'm closing this as I'm guessing you've abandoned this project. I appreciate the great work! :)

Seeing as there are some minor things missing from this library (eg. no TS types and IE11 incompatabilities), I've decided to fork it and continue the work by myself. You can find the new project here: [https://github.com/Ekman/empty-php](https://github.com/Ekman/empty-php). We're using this at my work place and want to be able to develop it if needed.

**Comment by vvmspace** [comment]
My telegram:
@vvmspace

**Pull request closed without merging**
